services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"   
    depends_on:
      - db
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"   
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017" 

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local